---
- hosts: all
  become: "{{ 'no' if packer_builder_type == 'docker' else 'yes' }}"

  tasks:
    - name: Install Squid and Packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - squid
        - sudo
    - name: Squid Configuration
      template:
        dest: /etc/squid/squid.conf
        src: files/squid.conf
    - name: Squid Iptables
      template:
        dest: /etc/sysconfig/iptables
        src:  files/iptables
    - name: Ensure Squid will start on boot
      service:
        name: squid
        enabled: yes
    - name: Ensure SSH enabled
      package:
        name: openssh
        state: present
      when: packer_builder_type != 'docker'

